### ISSUE TITLE
autocomplete should get binaries from $PATH

### ISSUE THREAD

**Issue by sammy-ette** [dacousb/sheesh#1]
looking through the code, i notice that the only directory opened was a single bin folder.
sheesh should check all directories in $PATH instead

**Comment by dacousb** [comment]
I have been looking into it to see if there is a way to implement it, however PATH is an environment variable, and sheesh does not support variables (for now). Also, actually, PATH contains addresses like /usr/bin, and many others, so the functionality, would be the same with or without variable. I must admit however, that it would be very convenient if the variable existed, but we will have to wait for the variables to be implemented.
